# Copyright (c) 2026 Kutay Demir.
# Licensed under the PolyForm Shield License 1.0.0. See LICENSE file for details.

"""Install the PyLCSS auto-export observer as a FreeCAD Mod.

Why this exists
---------------
We initially passed ``pylcss_autoexport.FCMacro`` as a positional CLI
argument to ``freecad.exe`` hoping it would run on startup.  Empirically
FreeCAD 1.x does NOT auto-execute ``.FCMacro`` arguments -- it tries to
open them as documents, fails silently, and the observer never installs.
End-symptom: the user saves in FreeCAD, no ``.brep`` / ``.fcmeta.json``
appear next to the ``.FCStd``, PyLCSS keeps logging "no BREP yet".

The canonical way to get a Python hook loaded on every FreeCAD start is
to drop an ``InitGui.py`` into a Mod directory under FreeCAD's user
config root.  FreeCAD's startup walks ``Mod/<name>/InitGui.py`` and runs
each one automatically.  We install our observer there.

Idempotent: the installer overwrites the InitGui.py only when its
contents change, so future PyLCSS upgrades can ship a newer observer
without leaving stale copies behind.
"""

from __future__ import annotations

import logging
import os
import platform
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


# Bundled observer macro -- the file the launcher used to pass on the
# command line.  Loaded once and copied into FreeCAD's Mod dir as InitGui.py.
_MACRO_FILE = Path(__file__).resolve().parent / "macros" / "pylcss_autoexport.FCMacro"


# InitGui.py wrapper that just executes our macro at FreeCAD startup.
# Kept as a tiny wrapper instead of inlining the macro so future updates
# to the macro automatically take effect via the launcher's idempotent
# install -- we don't have to remember to update two files.
_INITGUI_TEMPLATE = '''\
# Auto-generated by PyLCSS (pylcss/cad/freecad_bridge/mod_installer.py).
# Do not edit by hand -- it gets overwritten on the next PyLCSS launch.
#
# This Mod registers a PyLCSS document observer so that every save inside
# FreeCAD writes a sibling <doc>.brep + <doc>.fcmeta.json that PyLCSS
# auto-imports.  Without this hook, PyLCSS can't see geometry the user
# draws in FreeCAD.

import os
import traceback

try:
    import FreeCAD
    _MACRO_PATH = {macro_path_literal}
    if os.path.isfile(_MACRO_PATH):
        with open(_MACRO_PATH, "r", encoding="utf-8") as _fh:
            exec(_fh.read(), {{"__file__": _MACRO_PATH, "__name__": "__pylcss_autoexport__"}})
    else:
        FreeCAD.Console.PrintWarning(
            "[PyLCSS] auto-export macro not found at {{0}} -- save events will NOT "
            "produce sidecar files for PyLCSS to pick up.\\n".format(_MACRO_PATH)
        )
except Exception:
    try:
        FreeCAD.Console.PrintError(
            "[PyLCSS] auto-export Mod failed to install observer:\\n"
            + traceback.format_exc() + "\\n"
        )
    except Exception:
        pass
'''


def freecad_user_config_root() -> Optional[Path]:
    """Return the root of FreeCAD's per-user config directory.

    FreeCAD 1.x bumped this from a flat ``FreeCAD/`` to a **versioned**
    subdir like ``FreeCAD/v1-1/`` -- a Mod dropped into the flat parent
    is silently ignored.  We probe the versioned subdir first (newest
    semver wins), then fall back to the flat path for 0.x users still
    on the LTS.

    Windows: ``%APPDATA%/FreeCAD/v<major>-<minor>/`` (or ``%APPDATA%/FreeCAD``)
    Linux:   ``~/.FreeCAD/v...`` / ``~/.config/FreeCAD/v...``
    macOS:   ``~/Library/Preferences/FreeCAD/v...``
    """
    sysname = platform.system()
    if sysname == "Windows":
        appdata = os.environ.get("APPDATA")
        if not appdata:
            return None
        base = Path(appdata) / "FreeCAD"
    elif sysname == "Darwin":
        base = Path(os.path.expanduser("~")) / "Library" / "Preferences" / "FreeCAD"
    else:
        xdg = os.environ.get("XDG_CONFIG_HOME")
        cfg = Path(xdg) if xdg else Path(os.path.expanduser("~/.config"))
        base = cfg / "FreeCAD"
        if not base.exists():
            base = Path(os.path.expanduser("~/.FreeCAD"))

    if not base.exists():
        # FreeCAD hasn't run yet -- nothing to install into.  Return the
        # versioned-looking path anyway so the caller can mkdir; FreeCAD
        # will scan whatever's there on next start.
        return base

    # Pick the newest "v<major>-<minor>" subdir if any exist; that's
    # FreeCAD 1.x's actual config root.  Fall back to the flat path.
    versioned = sorted(
        (p for p in base.iterdir() if p.is_dir() and p.name.startswith("v")
         and "-" in p.name),
        key=lambda p: _parse_version(p.name),
        reverse=True,
    )
    if versioned:
        return versioned[0]
    return base


def _parse_version(name: str) -> tuple:
    """Best-effort ``"v1-1"`` -> ``(1, 1)`` so ``sorted`` picks newest."""
    try:
        digits = name.lstrip("v").split("-")
        return tuple(int(p) for p in digits)
    except Exception:
        return (0,)


def install_pylcss_mod() -> bool:
    """Idempotently write ``<freecad-user-config>/Mod/PyLCSS/InitGui.py``.

    Returns True when the Mod is present + up to date after this call
    (whether or not we actually wrote anything).
    """
    if not _MACRO_FILE.is_file():
        logger.warning(
            "PyLCSS auto-export macro missing at %s; cannot install Mod.",
            _MACRO_FILE,
        )
        return False

    root = freecad_user_config_root()
    if root is None:
        logger.warning("Couldn't locate FreeCAD user config root; skipping Mod install.")
        return False

    mod_dir = root / "Mod" / "PyLCSS"
    init = mod_dir / "Init.py"
    initgui = mod_dir / "InitGui.py"

    desired = _INITGUI_TEMPLATE.format(macro_path_literal=repr(str(_MACRO_FILE)))
    try:
        mod_dir.mkdir(parents=True, exist_ok=True)
        # Init.py runs on EVERY FreeCAD start (GUI + headless FreeCADCmd).
        # That second path matters for the param-writer pipeline below --
        # without it the observer wouldn't be active when we headlessly
        # apply a parameter change, and the BREP / sidecar wouldn't get
        # re-emitted after recompute+save.
        if not (init.is_file() and init.read_text(encoding="utf-8") == desired):
            init.write_text(desired, encoding="utf-8")
            logger.info("Installed PyLCSS FreeCAD Mod at %s", init)
        # Keep InitGui.py in sync too so a 0.x user (which only loads
        # InitGui) still gets the observer.  Same content, idempotent.
        if not (initgui.is_file() and initgui.read_text(encoding="utf-8") == desired):
            initgui.write_text(desired, encoding="utf-8")
        return True
    except Exception as exc:
        logger.warning("Failed to install PyLCSS FreeCAD Mod under %s: %s", mod_dir, exc)
        return False
