# Copyright (c) 2026 Kutay Demir.
# Licensed under the PolyForm Shield License 1.0.0. See LICENSE file for details.

"""Compile NodeGraphQt system graphs into executable Python source."""

from __future__ import annotations

import keyword
import re
from typing import Any

from .codegen import (
    BLOCK_NODE as _BLOCK_NODE,
    INPUT_NODE as _INPUT_NODE,
    INTERMEDIATE_NODE as _INTERMEDIATE_NODE,
    OUTPUT_NODE as _OUTPUT_NODE,
    RESERVED_NAMES as _RESERVED_NAMES,
    GraphCompilationError,
    as_bool as _as_bool,
    block_function_source as _block_function_source,
    connected_value as _connected_value,
    is_node as _is_node,
    only_port as _only_port,
    plot_color as _plot_color,
    property_value as _property,
    require_identifier as _require_identifier,
    safe_node_id as _safe_node_id,
    single_source as _single_source,
    topological_nodes as _topological_nodes,
    wrapper_source as _wrapper_source,
)
from .types import InputSpec, OutputSpec


class GraphBuilder:
    """Convert a NodeGraphQt graph into a public model function."""

    def __init__(self, graph: Any) -> None:
        self.graph = graph
        self.used_names: set[str] = set()

    def _sanitize_name(self, name: str) -> str:
        """Create a valid internal identifier from a user-facing label."""

        clean = re.sub(r"\W+", "_", str(name).strip(), flags=re.UNICODE).strip("_")
        if not clean:
            clean = "block"
        if clean[0].isdigit():
            clean = f"_{clean}"
        if keyword.iskeyword(clean) or clean in _RESERVED_NAMES:
            clean = f"block_{clean}"
        return clean

    def _get_unique_name(self, base_name: str) -> str:
        clean = self._sanitize_name(base_name)
        candidate = clean
        suffix = 2
        while candidate in self.used_names:
            candidate = f"{clean}_{suffix}"
            suffix += 1
        self.used_names.add(candidate)
        return candidate

    def build_system_model(
        self,
        function_name: str = "system_function",
        global_reserved_names: set[str] | None = None,
    ) -> tuple[str, list[InputSpec], list[OutputSpec]]:
        """Build source plus input/output metadata for the graph."""

        _require_identifier(function_name, "function name")
        nodes = list(self.graph.all_nodes())
        input_nodes = [node for node in nodes if _is_node(node, _INPUT_NODE)]
        output_nodes = [node for node in nodes if _is_node(node, _OUTPUT_NODE)]
        if not input_nodes:
            raise GraphCompilationError("The graph has no input nodes.")
        if not output_nodes:
            raise GraphCompilationError("The graph has no output nodes.")

        self.used_names = {function_name}
        if global_reserved_names:
            self.used_names.update(global_reserved_names)

        inputs, input_names = self._collect_inputs(input_nodes)
        outputs, output_names = self._collect_outputs(output_nodes)
        ordered_nodes = _topological_nodes(nodes)
        blocks = [
            node
            for node in ordered_nodes
            if _is_node(node, _BLOCK_NODE) or _is_node(node, _INTERMEDIATE_NODE)
        ]

        lines = [
            "import os",
            "import numpy as np",
            "from pylcss.design_studio import runtime as cad",
            "",
            "# Generated by pylcss.system_modeling.compiler.",
            "BASE_DIR = os.path.dirname(os.path.abspath(__file__))",
            "",
        ]

        surrogate_names = self._emit_surrogate_loaders(lines, blocks)
        for block in blocks:
            if not _is_node(block, _BLOCK_NODE):
                continue
            block_name = self._allocate_block_name(block, global_reserved_names)
            lines.extend(
                _block_function_source(
                    block,
                    block_name,
                    surrogate_names.get(block.id),
                )
            )

        core_name = f"_{function_name}_core"
        arguments = ", ".join(item["name"] for item in inputs)
        lines.append(f"def {core_name}({arguments}):")
        lines.extend(
            self._core_body(
                blocks,
                input_nodes,
                output_nodes,
                input_names,
                output_names,
            )
        )
        lines.extend(_wrapper_source(function_name, core_name, inputs))

        source = "\n".join(lines).rstrip() + "\n"
        try:
            compile(source, f"<generated {function_name}>", "exec")
        except SyntaxError as exc:
            raise GraphCompilationError(
                f"Generated source is invalid at line {exc.lineno}: {exc.msg}."
            ) from exc
        return source, inputs, outputs

    def build_spy_model(
        self,
        nodes: list[Any],
        input_nodes: list[Any],
        output_nodes: list[Any],
        target_node_id: str,
        function_name: str = "spy_model",
    ) -> tuple[str, list[dict[str, str]], list[dict[str, str]]]:
        """Build the training probe used by the surrogate-modeling UI."""

        from .spy_compiler import build_spy_model

        return build_spy_model(
            nodes,
            input_nodes,
            output_nodes,
            target_node_id,
            function_name,
        )

    def _collect_inputs(
        self,
        nodes: list[Any],
    ) -> tuple[list[InputSpec], dict[str, str]]:
        specs: list[InputSpec] = []
        names_by_id: dict[str, str] = {}
        for node in nodes:
            props = _property(node, "input_props")
            if not isinstance(props, dict):
                props = {}
            raw_name = props.get("var_name", _property(node, "var_name"))
            name = _require_identifier(raw_name, f"input on {node.name()!r}")
            self._reserve_interface_name(name)
            names_by_id[node.id] = name
            specs.append(
                {
                    "name": name,
                    "display_name": name,
                    "unit": props.get("unit", _property(node, "unit", "-")),
                    "min": props.get("min", _property(node, "min", "0.0")),
                    "max": props.get("max", _property(node, "max", "10.0")),
                    "type": "continuous",
                    "granularity": 1.0,
                }
            )
        return specs, names_by_id

    def _collect_outputs(
        self,
        nodes: list[Any],
    ) -> tuple[list[OutputSpec], dict[str, str]]:
        specs: list[OutputSpec] = []
        names_by_id: dict[str, str] = {}
        for node in nodes:
            props = _property(node, "output_props")
            if not isinstance(props, dict):
                props = {}
            raw_name = props.get("var_name", _property(node, "var_name"))
            name = _require_identifier(raw_name, f"output on {node.name()!r}")
            self._reserve_interface_name(name)
            names_by_id[node.id] = name
            specs.append(
                {
                    "name": name,
                    "display_name": name,
                    "unit": props.get("unit", _property(node, "unit", "-")),
                    "req_min": props.get(
                        "req_min", _property(node, "req_min", "-1e9")
                    ),
                    "req_max": props.get(
                        "req_max", _property(node, "req_max", "1e9")
                    ),
                    "minimize": bool(_property(node, "minimize", False)),
                    "maximize": bool(_property(node, "maximize", False)),
                    "show_in_legend": bool(
                        _property(node, "show_in_legend", True)
                    ),
                    "color": _plot_color(node),
                }
            )
        return specs, names_by_id

    def _reserve_interface_name(self, name: str) -> None:
        if name in self.used_names:
            raise GraphCompilationError(
                f"Duplicate or reserved variable name: {name!r}."
            )
        self.used_names.add(name)

    def _allocate_block_name(
        self,
        block: Any,
        global_reserved_names: set[str] | None,
    ) -> str:
        name = self._get_unique_name(block.name())
        if global_reserved_names is not None:
            while name in global_reserved_names:
                name = self._get_unique_name(name)
            global_reserved_names.add(name)
        block.set_property("func_name", name)
        return name

    def _emit_surrogate_loaders(
        self,
        lines: list[str],
        blocks: list[Any],
    ) -> dict[str, str]:
        surrogate_names: dict[str, str] = {}
        surrogate_blocks = [
            block
            for block in blocks
            if _is_node(block, _BLOCK_NODE)
            and _as_bool(_property(block, "use_surrogate", False))
            and _property(block, "surrogate_model_path")
        ]
        if not surrogate_blocks:
            return surrogate_names

        lines.extend(
            [
                "import joblib",
                "",
                "def _load_surrogate(path):",
                "    candidates = [path]",
                "    if not os.path.isabs(path):",
                "        candidates.extend([",
                "            os.path.join(os.getcwd(), path),",
                "            os.path.join(BASE_DIR, path),",
                "        ])",
                "    for candidate in candidates:",
                "        if os.path.isfile(candidate):",
                "            return joblib.load(candidate)",
                "    raise FileNotFoundError(f'Surrogate model not found: {path}')",
                "",
            ]
        )
        for block in surrogate_blocks:
            model_name = f"_surrogate_{_safe_node_id(block.id)}"
            path = str(_property(block, "surrogate_model_path"))
            lines.append(f"{model_name} = _load_surrogate({path!r})")
            surrogate_names[block.id] = model_name
        lines.append("")
        return surrogate_names

    def _core_body(
        self,
        blocks: list[Any],
        input_nodes: list[Any],
        output_nodes: list[Any],
        input_names: dict[str, str],
        output_names: dict[str, str],
    ) -> list[str]:
        lines: list[str] = []
        values: dict[tuple[str, str], str] = {}

        for node in input_nodes:
            ports = list(node.output_ports())
            if not ports:
                raise GraphCompilationError(
                    f"Input node {node.name()!r} has no output port."
                )
            values[(node.id, ports[0].name())] = input_names[node.id]

        for block in blocks:
            if _is_node(block, _INTERMEDIATE_NODE):
                input_port = _only_port(block.input_ports(), block, "input")
                source = _single_source(input_port, block)
                expression = _connected_value(values, source, block)
                variable = self._get_unique_name(
                    _require_identifier(
                        _property(block, "var_name"),
                        f"intermediate on {block.name()!r}",
                    )
                )
                lines.append(f"    {variable} = {expression}")
                output_port = _only_port(block.output_ports(), block, "output")
                values[(block.id, output_port.name())] = variable
                continue

            call_arguments = [
                _connected_value(values, _single_source(port, block), block)
                for port in block.input_ports()
            ]
            function = _property(block, "func_name")
            if not isinstance(function, str) or not function:
                raise GraphCompilationError(
                    f"Function name was not assigned for block {block.name()!r}."
                )
            result_names: list[str] = []
            for port in block.output_ports():
                _require_identifier(port.name(), f"output port on {block.name()!r}")
                result_name = f"_v_{_safe_node_id(block.id)}_{port.name()}"
                result_names.append(result_name)
                values[(block.id, port.name())] = result_name
            call = f"{function}({', '.join(call_arguments)})"
            if result_names:
                lines.append(f"    {', '.join(result_names)} = {call}")
            else:
                lines.append(f"    {call}")

        entries: list[str] = []
        for node in output_nodes:
            input_port = _only_port(node.input_ports(), node, "input")
            source = _single_source(input_port, node)
            expression = _connected_value(values, source, node)
            entries.append(f"{output_names[node.id]!r}: {expression}")
        lines.append(f"    return {{{', '.join(entries)}}}")
        return lines


__all__ = ["GraphBuilder", "GraphCompilationError"]
