# Copyright (c) 2026 Kutay Demir.
# Licensed under the PolyForm Shield License 1.0.0. See LICENSE.
"""Report rendering kept separate from tabular and scientific data export."""

from __future__ import annotations

import base64
import mimetypes
from collections.abc import Mapping, Sequence
from html import escape
from pathlib import Path
from typing import Any, Literal

from pylcss.io_manager._atomic import PathLike, atomic_text_writer

ReportFormat = Literal["html", "md", "markdown"]
ReportSection = Mapping[str, Any]

_STYLE = """
body { font-family: "Segoe UI", sans-serif; margin: 40px;
       background: #1e1f22; color: #e0e0e0; }
h1 { color: #d29922; border-bottom: 2px solid #d29922; padding-bottom: 10px; }
h2 { color: #d29922; }
table { border-collapse: collapse; width: 100%; margin: 20px 0; }
th, td { border: 1px solid #444; padding: 8px; text-align: left; }
th { background: #2b2d30; color: #d29922; }
tr:nth-child(even) { background: #2b2d30; }
.metric { display: inline-block; margin: 10px; padding: 15px;
          background: #2b2d30; border-radius: 8px;
          border-left: 4px solid #d29922; }
.metric-value { font-size: 24px; font-weight: bold; color: #d29922; }
.metric-label { font-size: 12px; color: #aaa; }
img { max-width: 100%; border-radius: 4px; }
""".strip()


def _mapping(value: object, field: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise TypeError(f"Report field '{field}' must be a mapping.")
    return value


def _sequence(value: object, field: str) -> Sequence[Any]:
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        raise TypeError(f"Report field '{field}' must be a sequence.")
    return value


def _image_data_uri(value: PathLike) -> str:
    path = Path(value)
    media_type, _ = mimetypes.guess_type(path.name)
    if media_type is None or not media_type.startswith("image/"):
        raise ValueError(f"Cannot determine an image media type for {path.name}.")
    payload = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{media_type};base64,{payload}"


def _html_report(title: str, sections: Sequence[ReportSection]) -> str:
    output = [
        "<!DOCTYPE html>",
        '<html lang="en"><head><meta charset="utf-8">',
        f"<title>{escape(title)}</title>",
        f"<style>{_STYLE}</style></head><body>",
        f"<h1>{escape(title)}</h1>",
        "<p>Generated by PyLCSS</p>",
    ]
    for section in sections:
        if "heading" in section:
            output.append(f"<h2>{escape(str(section['heading']))}</h2>")
        if "text" in section:
            output.append(f"<p>{escape(str(section['text']))}</p>")
        if "metrics" in section:
            for name, value in _mapping(section["metrics"], "metrics").items():
                output.append(
                    '<div class="metric">'
                    f'<div class="metric-value">{escape(str(value))}</div>'
                    f'<div class="metric-label">{escape(str(name))}</div></div>'
                )
        if "table" in section:
            table = _mapping(section["table"], "table")
            output.append("<table>")
            if "headers" in table:
                headers = _sequence(table["headers"], "table.headers")
                cells = "".join(f"<th>{escape(str(value))}</th>" for value in headers)
                output.append(f"<thead><tr>{cells}</tr></thead>")
            output.append("<tbody>")
            for row in _sequence(table.get("rows", ()), "table.rows"):
                values = _sequence(row, "table row")
                cells = "".join(f"<td>{escape(str(value))}</td>" for value in values)
                output.append(f"<tr>{cells}</tr>")
            output.append("</tbody></table>")
        if "image" in section:
            source = escape(_image_data_uri(section["image"]), quote=True)
            alt = escape(str(section.get("heading", "Report image")), quote=True)
            output.append(f'<img src="{source}" alt="{alt}">')
    output.append("</body></html>")
    return "\n".join(output) + "\n"


def _markdown_text(value: object) -> str:
    return str(value).replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")


def _markdown_report(title: str, sections: Sequence[ReportSection]) -> str:
    output = [f"# {title}", "", "*Generated by PyLCSS*", ""]
    for section in sections:
        if "heading" in section:
            output.extend((f"## {section['heading']}", ""))
        if "text" in section:
            output.extend((str(section["text"]), ""))
        if "metrics" in section:
            for name, value in _mapping(section["metrics"], "metrics").items():
                output.append(f"- **{name}**: {value}")
            output.append("")
        if "table" in section:
            table = _mapping(section["table"], "table")
            headers = _sequence(table.get("headers", ()), "table.headers")
            if headers:
                output.append(
                    "| " + " | ".join(_markdown_text(value) for value in headers) + " |"
                )
                output.append("| " + " | ".join("---" for _ in headers) + " |")
            for row in _sequence(table.get("rows", ()), "table.rows"):
                values = _sequence(row, "table row")
                output.append(
                    "| " + " | ".join(_markdown_text(value) for value in values) + " |"
                )
            output.append("")
        if "image" in section:
            alt = _markdown_text(section.get("heading", "Report image"))
            output.extend((f"![{alt}]({_image_data_uri(section['image'])})", ""))
    return "\n".join(output).rstrip() + "\n"


def write_report(
    path: PathLike,
    title: str,
    sections: Sequence[ReportSection],
    report_format: ReportFormat,
) -> None:
    """Validate, render, and atomically write a report."""
    if report_format == "html":
        content = _html_report(title, sections)
    elif report_format in {"md", "markdown"}:
        content = _markdown_report(title, sections)
    else:
        raise ValueError(f"Unsupported report format: {report_format}")

    with atomic_text_writer(path, encoding="utf-8", newline="\n") as handle:
        handle.write(content)
